name: "功能请求"
description: "为 Reden Mod 提供方案或解决思路"
title: "[功能请求]: <在此处简单描述一些你将要请求的功能>"
labels: ["enhancement"]
assignees: ["zly2006", "Cubik65536"]

body:
  - type: markdown
    attributes:
      value: |
        感谢您为 Reden Mod 提供新的方案或解决思路！
        
        > ### 重要！ :warning:
        > 
        > issue 专为报告问题以及请求新功能而设。这意味着我们不会在此处接受任何关于使用的问题。
        > 如果您打开的 issue 不符合要求，它将被关闭。
        >
        > 对于使用上的问题，请参考以下资源：
        > * [加入 QQ 群](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=FydjtxbXtobkK9aYrLt9zwW_CVi4Ep2n&authKey=%2BLarhXwt%2BZF2K9GpL9obcswcHff3A%2BkwekRQ9S4wxu0teuFqXIR9Pi5FrJXnv3Bc&noverify=0&group_code=708842363)
        > * [加入 Discord 服务器](https://discord.gg/jUUPjgyAz5)

  - type: checkboxes
    id: confirm
    attributes:
      label: 请选择：
      description: 如果您是开发者并且愿意为 Reden Mod 贡献代码来实现这个功能，请勾选以下选项。
      options:
        - label: 我正在着手增加这个功能
          required: false

  - type: textarea
    id: solution-description
    validations:
      required: true
    attributes:
      label: 描述您想要的解决方案
      description: 清晰简洁的描述您想要的解决方案

  - type: textarea
    id: alternative-description
    attributes:
      label: 描述您考虑过的替代方案
      description: 清晰简洁的描述您考虑过的替代解决方案或功能。

  - type: textarea
    id: anything-else
    attributes:
      label: 还有其他的吗？
      description: 在此处添加任何与功能请求相关的内容、代码示例或现有实现。

  - type: markdown
    attributes:
      value: |
        ---------
        
        在您提交本 issue 之前，请确认以下内容：
        
        **1. 是否已经有现有的 issue 请求了这个功能？**
        
        请确认是否已经有与该功能请求的 issue。
        
        ---------

  - type: checkboxes
    id: terms
    attributes:
      label: 请确认以下条款
      options:
        - label: 我已经查看了 [已有 issue](https://github.com/zly2006/reden-is-what-we-made/issues) 并确定没有人提交过与此功能请求相关的 issue
          required: true