name: "其他问题"
description: "其他类型的问题"
title: "[其他]: "

body:
  - type: markdown
    attributes:
      value: |
        > ### 重要！ :warning:
        > 
        > issue 专为报告问题以及请求新功能而设。这意味着我们不会在此处接受任何关于使用的问题。
        > 如果您打开的 issue 不符合要求，它将被关闭。
        >
        > 对于使用上的问题，请参考以下资源：
        > * [加入 QQ 群](http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=FydjtxbXtobkK9aYrLt9zwW_CVi4Ep2n&authKey=%2BLarhXwt%2BZF2K9GpL9obcswcHff3A%2BkwekRQ9S4wxu0teuFqXIR9Pi5FrJXnv3Bc&noverify=0&group_code=708842363)
        > * [加入 Discord 服务器](https://discord.gg/jUUPjgyAz5)

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 描述
